repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: [--quiet]
        language: system
        types: [python]

      - id: ruff
        name: ruff
        entry: ruff
        args: [check, --fix]
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        # limit mypy to your package to keep it fast at first
        args: [src]
        language: system
        types: [python]
