repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: [--quiet]
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff
        args: [check, --fix]
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        args: [-p, sierra_sync]
        language: system
        types: [python]
        pass_filenames: false
